/* ============================================================
   THE LOST LIBRARIES — shared dataset
   Loaded by index.html, map.html and timeline.html before each
   page's own script. One copy of the record set, so the three
   pages cannot drift apart the way they did when each held its
   own: the map once sat at 108 records while the page said 114.

   Record shape
     name      display name
     location  place, as shown to the reader
     year      negative for BC
     cause     key into CAUSES below
     lat, lon  decimal degrees, for the map and timeline
     perp      who did it
     desc      the entry text
     isNew     true if added beyond the original source dataset
     approx    true if the record covers a whole country or region
               rather than one building (drawn as a dashed ring)
   ============================================================ */

/* Cause colours live here, not in the page CSS, because the charts
   and map pins are painted from JavaScript. All pass WCAG AA on the
   paper background. If you change one, change --c-* in styles.css to
   match so the legend and the chart agree. */
/* ------------------------------------------------------------
   SOURCES

   Every record carries at least one citation. Be clear on what each
   tier means:

   - "list" is the Wikipedia survey this dataset was compiled from.
     It is the project's honest provenance, not independent
     verification of that particular entry.
   - The named sources below were read directly while compiling or
     correcting records, and are cited only on entries they support.

   Where an entry rests on a single chronicler, a disputed figure or
   a traditional account, the record text says so rather than hiding
   it behind a citation.
   ------------------------------------------------------------ */
var SOURCES = {
  caesarea: { label: "Evans, 'Longevity of Late Antique Autographs and First Copies', in Scribes and Their Remains (2020)", note: "Also Bull, 'Caesarea Maritima: The Search for Herod's City', Biblical Archaeology Review 8(3), 1982." },
  halbert: { label: "Ministry of Education, Saint Christopher and Nevis: Charles A. Halbert Public Library", url: "https://web.archive.org/web/20111008001722/http://www.moeskn.org/index.php?option=com_content&view=article&id=29&Itemid=92" },
  trove_sms: { label: "Moore, 'Fire brought death to house of tranquility' (1983), via Trove", url: "https://trove.nla.gov.au/newspaper/article/270604157" },
  newcollege: { label: "Sarasota Herald-Tribune: New College of Florida tosses hundreds of library books, empties gender diversity library", url: "https://www.heraldtribune.com/story/news/education/2024/08/15/new-college-of-florida-throws-away-hundreds-of-library-books-diversity-lgbtq/74814756007/" },
  unesco_lost: { label: "UNESCO: Lost Memory \u2014 Libraries and Archives Destroyed in the Twentieth Century (1996)", url: "http://www.unesco.org/new/en/communication-and-information/resources/publications-and-communication-materials/publications/full-list/lost-memory-libraries-and-archives-destroyed-in-the-twentieth-century/", note: "Van der Hoeven & van Albada. The standard survey for 20th-century losses." },
  civallero: { label: "Civallero, 'When Memory Turns into Ashes: Memoricide During the XX Century'", url: "http://libr.org/isc/issues/ISC25/articles/WHEN%20MEMORY%20TURNS%20INTO%20ASHES.pdf" },
  raven: { label: "Raven (ed.), Lost Libraries: The Destruction of Great Book Collections Since Antiquity (2004)" },
  list: { label: "Wikipedia: List of destroyed libraries", url: "https://en.wikipedia.org/wiki/List_of_destroyed_libraries", note: "The survey this dataset was compiled from." },
  nybooks_alex: { label: "Lewis & Lloyd-Jones, 'The Vanished Library', New York Review of Books", url: "http://www.nybooks.com/articles/3517" },
  alexandria: { label: "Wikipedia: Library of Alexandria", url: "https://en.wikipedia.org/wiki/Library_of_Alexandria" },
  gozo: { label: "The Malta Independent: documents from Gozo dating to 1431 saved from the bin", url: "https://web.archive.org/web/20190506001141/http://www.independent.com.mt/articles/2015-05-23/local-news/Documents-from-Gozo-dating-to-1431-saved-from-the-bin-6736135676" },
  zaluski: { label: "Witt, 'The Strange Life of One of the Greatest European Libraries of the Eighteenth Century', FYI France", url: "https://web.archive.org/web/20210301040701/https://www.fyifrance.com/f102005c.htm" },
  loc: { label: "Library of Congress: Jefferson's Legacy \u2014 a brief history", url: "https://www.loc.gov/loc/legacy/loc.html" },
  jaffna: { label: "Knuth, 'Destroying a Symbol: Checkered History of Sri Lanka's Jaffna Public Library' (IFLA)", url: "http://www.ifla.org/IV/ifla72/papers/119-Knuth-en.pdf" },
  sikh: { label: "Indian Express: the mystery of the missing articles of the Sikh Reference Library", url: "https://web.archive.org/web/20201225164840/https://indianexpress.com/article/explained/the-mystery-of-missing-articles-of-sikh-reference-library-5789595/" },
  riedlmayer_erasing: { label: "Riedlmayer, 'Erasing the Past: The Destruction of Libraries and Archives in Bosnia-Herzegovina' (1995)", url: "https://web.archive.org/web/20120118204551/http://fp.arizona.edu/mesassoc/Bulletin/bosnia.htm" },
  riedlmayer_crimes: { label: "Riedlmayer, 'Crimes of war, crimes of peace', Library Trends 56(1)", url: "https://doi.org/10.1353%2Flib.2007.0057", note: "Peer-reviewed; basis of ICTY testimony." },
  harvard: { label: "Harvard Gazette: cataloguing cultural destruction in the Balkans", url: "https://news.harvard.edu/gazette/story/2020/02/harvard-librarian-puts-this-war-crime-on-the-map" },
  nub: { label: "University of Sarajevo: anniversary of the City Hall destruction", url: "https://unsa.ba/en/node/2708" },
  bih_court: { label: "Court of Bosnia & Herzegovina: custody of the suspects terminated", url: "http://www.sudbih.gov.ba/?id=3190&jezik=e" },
  bbc_iraq: { label: "BBC: prized Iraqi annals 'lost in blaze'", url: "https://news.bbc.co.uk/2/hi/middle_east/2948021.stm" },
  guardian_isis: { label: "The Guardian: ISIS destroys thousands of books and manuscripts in Mosul libraries", url: "https://www.theguardian.com/books/2015/feb/26/isis-destroys-thousands-books-libraries" },
  ows: { label: "Progressive Librarian: Occupy Wall Street librarians speak out", url: "http://www.progressivelibrariansguild.org/PL/PL38_39/003.pdf" },
  elpais_egypt: { label: "El Pa\u00eds: fire during Cairo unrest destroys the original Description de l'\u00c9gypte", url: "https://web.archive.org/web/20210126031501/https://elpais.com/cultura/2011/12/18/actualidad/1324162801_850215.html", note: "In Spanish." },
  guardian_timbuktu: { label: "The Guardian: Timbuktu mayor says rebels torched library of historic manuscripts", url: "https://www.theguardian.com/world/2013/jan/28/mali-timbuktu-library-ancient-manuscripts", note: "The initial report; see the Foreign Policy piece for the correction." },
  fp_timbuktu: { label: "Foreign Policy: how many of Timbuktu's manuscripts were destroyed?", url: "https://foreignpolicy.com/2013/01/28/how-many-of-timbuktus-priceless-manuscripts-were-destroyed/", note: "The reporting that corrected the early 'everything was lost' headlines." },
  tyee: { label: "The Tyee: secret memo casts doubt on federal science library closures", url: "https://thetyee.ca/News/2013/12/30/Harper-Library-Closures/" },
  naharnet: { label: "Naharnet: Tripoli figures condemn torching of famed library", url: "http://www.naharnet.com/stories/en/112570-tripoli-figures-condemn-torching-famed-library-as-father-sarrouj-forgives-attackers" },
  lor_sa: { label: "Lor, 'Burning Libraries for the People', Libri 63(4)", url: "https://repository.up.ac.za/bitstream/handle/2263/37230/Lor_Burning_2013.pdf?sequence=3&isAllowed=y" },
  independent_ukzn: { label: "The Independent: 'Nazi-style' book burning at UKZN condemned", url: "https://www.independent.co.uk/news/world/africa/ukzn-south-africa-university-protests-nazistyle-library-book-burning-rape-brutality-a7230296.html" },
  bbc_bihar: { label: "BBC News: Bihar Sharif \u2014 the 113-year-old India library torched in a riot", url: "https://www.bbc.com/news/world-asia-india-65308394" },
  aljaz_bihar: { label: "Al Jazeera: India town mourns burning of historic library at Muslim school", url: "https://www.aljazeera.com/news/2023/4/10/india-town-mourns-burning-of-historic-library-at-muslim-school" },
  lap_gaza: { label: "Librarians and Archivists with Palestine: Israeli damage to archives, libraries and museums in Gaza", url: "https://librarianswithpalestine.org/gaza-report-2024/", note: "Field report, October 2023 \u2013 January 2024." },
  gaza_inv: { label: "Gaza, inventaire d'un patrimoine bombard\u00e9: Rashad al-Shawwa Cultural Center", url: "https://gazahistoire.hypotheses.org/3161", note: "In French." },
  gaza_wiki: { label: "Wikipedia: Destruction of cultural heritage during the Gaza war", url: "https://en.wikipedia.org/wiki/Destruction_of_cultural_heritage_during_the_Gaza_war" },
  sudan_wiki: { label: "Wikipedia: Destruction of cultural heritage during the Sudanese civil war", url: "https://en.wikipedia.org/wiki/Destruction_of_cultural_heritage_during_the_Sudanese_civil_war" },
  unesco_ua: { label: "UNESCO: verified damaged cultural sites in Ukraine", url: "https://www.unesco.org/en/ukraine-war/damaged-cultural-sites", note: "Updated continuously; figures here are as of 29 September 2026." },
  lapl: { label: "Los Angeles Public Library: 30th anniversary of the 1986 fire", url: "https://www.lapl.org/collections-resources/blogs/lapl/april-29-marks-30th-anniversary-1986-fire" },
  abbey: { label: "Abbey Newsletter: the Leningrad library fire", url: "http://cool.conservation-us.org/byorg/abbey/an/an12/an12-4/an12-402.html" },
  bbc_norwich: { label: "BBC On This Day: library fire wipes out historic records (Norwich, 1994)", url: "https://news.bbc.co.uk/onthisday/hi/dates/stories/august/1/newsid_2526000/2526839.stm" },
  guardian_gsa: { label: "The Guardian: Glasgow School of Art fire damages the Mackintosh building", url: "https://www.theguardian.com/uk-news/2014/may/23/glasgow-school-art-fire-charles-rennie-mackintosh-live" },
  guardian_gsa2: { label: "The Guardian: Glasgow School of Art fire caused by gases from a foam canister", url: "https://www.theguardian.com/education/2014/nov/26/glasgow-school-of-art-fire-foam-canister-report" },
  scecsal_mzuzu: { label: "Dube, Kanyundo & Majawa, 'Coping with the fire disaster at Mzuzu University'", url: "https://www.scecsal.org/publications/papers2018/009_dube_2018.pdf" },
  ewn_jagger: { label: "Eyewitness News: fire wreaks destruction on UCT", url: "https://ewn.co.za/2021/04/18/fire-wreaks-massive-destruction-on-uct" },
  jagger_abd: { label: "Kirkwood, Noble & Singer, 'What we lost in the Jagger Library fire', Africa Bibliography", url: "https://doi.org/10.1017%2Fabd.2023.9" },
  qz_inion: { label: "Quartz: a Moscow library containing 14 million books is on fire", url: "http://qz.com/336926/a-moscow-library-containing-rare-un-documents-ancient-slavic-texts-and-14-million-books-is-on-fire/" },
  polastron: { label: "Polastron, Books on Fire (2007)" },
  ovenden: { label: "Ovenden, Burning the Books (2020)" },
  knuth: { label: "Knuth, Libricide (2003)" }
};

/* Resolve a record's src keys into source objects. */
function sourcesFor(lib){
  return (lib.src || ['list']).map(function(k){ return SOURCES[k]; })
                              .filter(function(s){ return !!s; });
}

var CAUSES = {
  war:      { label: 'Armed Conflict',   color: '#a8401a',
              desc: 'Foreign invasion, siege and civil war alike. The most consistent destroyer of libraries, from Bronze Age Mari to Gaza, Sudan and Ukraine today.' },
  religion: { label: 'Religious Purge',  color: '#5b4a9e',
              desc: 'Books deemed heretical or ideologically dangerous, burned by bishops, caliphs, Taliban commanders and ISIS militants alike.' },
  govt:     { label: 'State Censorship', color: '#7a5a1e',
              desc: 'Deliberate erasure ordered by governments, from Qin Shi Huang\'s book burnings to the Khmer Rouge to quiet modern budget cuts.' },
  fire:     { label: 'Accidental Fire',  color: '#9c5416',
              desc: 'The enemy with no ideology. Earthquakes, candles, oil lamps and careless flames have consumed what armies could not always reach.' },
  neglect:  { label: 'Neglect & Decay',  color: '#1e6b55',
              desc: 'Gradual dispersal and abandonment. Slow deaths that rarely make headlines but are no less permanent than fire.' }
};

var LIBRARIES = [
  /* 001 */ /* 001 */ { name: "Library of Zimri-Lim", location: "Mari, Mesopotamia", year: -1761, cause: "war", lat: 34.55, lon: 40.88, perp: "Hammurabi of Babylon", desc: "One of the oldest recorded library destructions in history. Hammurabi conquered Mari and razed its palace, destroying a vast archive of cuneiform tablets — one of the richest administrative and literary collections of the Bronze Age. The world's first documented biblioclasm.", src: ["polastron","list"] },
  /* 002 */ /* 002 */ { name: "Library of Ashurbanipal", location: "Nineveh, Neo-Assyrian Empire", year: -612, cause: "war", lat: 36.36, lon: 43.15, perp: "Coalition of Babylonians, Scythians & Medes", desc: "A supreme irony: the fire that destroyed Nineveh baked the clay tablets and preserved them for 2,600 years. The library held the Epic of Gilgamesh and the largest collection of the ancient Near East. Much of what we know of Mesopotamian literature survived precisely because the library burned.", src: ["polastron","list"] },
  /* 003 */ /* 003 */ { name: "Xianyang Palace and State Archives", location: "Xianyang, Qin China", year: -206, cause: "war", lat: 34.36, lon: 108.72, perp: "Xiang Yu", desc: "Rebel general Xiang Yu burned the Qin imperial palace for three months. The archives held records of the very book burnings Qin Shi Huang had ordered decades earlier — a destruction of the documentation of prior destruction. A recursive erasure spanning generations.", src: ["polastron","list"] },
  /* 004 */ /* 004 */ { name: "Library of Pergamon", location: "Pergamon, Asia Minor", year: -133, cause: "war", lat: 39.13, lon: 27.18, perp: "Rome / Mark Antony", isNew: true, desc: "The second greatest library of antiquity after Alexandria, holding an estimated 200,000 scrolls. When the last king of Pergamon bequeathed his kingdom to Rome, the library's fate became entangled in power struggles. Mark Antony allegedly stripped its entire contents and gave them to Cleopatra as a gift — transferring one civilisation's memory to another as a romantic gesture.", src: ["polastron","list"] },
  /* 005 */ /* 005 */ { name: "Library of Alexandria", location: "Alexandria, Egypt", year: -48, cause: "war", lat: 31.2, lon: 29.92, perp: "Disputed — Caesar, Aurelian, Theophilus & others", desc: "The most mythologized library destruction in history. Alexandria suffered multiple partial destructions across centuries, not one catastrophic burning. At its height it may have held 700,000 scrolls — the sum of ancient Mediterranean knowledge. Its loss was less an event than a slow bleed across four centuries.", src: ["nybooks_alex","alexandria","list"] },
  /* 006 */ /* 006 */ { name: "Imperial Library of Luoyang", location: "Luoyang, Han China", year: 189, cause: "war", lat: 34.68, lon: 112.45, perp: "Dong Zhuo", desc: "Warlord Dong Zhuo deliberately burned Luoyang to slow pursuing enemies. The imperial library, holding Han dynasty archives on silk and bamboo scrolls, burned with the city. Thousands of irreplaceable texts lost in a single afternoon of scorched-earth strategy.", src: ["polastron","list"] },
  /* 007 */ /* 007 */ { name: "Library of Celsus", location: "Ephesus, Asia Minor", year: 262, cause: "fire", lat: 37.94, lon: 27.34, perp: "Herulian invasion / earthquake", isNew: true, desc: "The third largest library of the ancient world, holding 12,000 scrolls. Built as a monument to the Roman senator Celsus, its magnificent facade still stands in modern Turkey. Destroyed in 262 AD during the Herulian sack of Ephesus, possibly preceded by an earthquake. The building survived as a shell for centuries after the knowledge inside was ash.", src: ["polastron","list"] },
  /* 008 */ /* 008 */ { name: "Library of Pantainos", location: "Athens, Roman Greece", year: 267, cause: "war", lat: 37.97, lon: 23.72, perp: "Heruli invasion", desc: "The Library of Pantainos, donated to Athens in the 2nd century AD, was destroyed during the Herulian invasion of 267. The Heruli sacked Athens in a devastating raid that wiped out much of the city's classical heritage. The library was never rebuilt.", src: ["polastron","list"] },
  /* 009 */ /* 009 */ { name: "Hadrian's Library", location: "Athens, Roman Greece", year: 267, cause: "war", lat: 37.975, lon: 23.725, perp: "Heruli invasion", desc: "Built by Emperor Hadrian in 132 AD, this vast complex held hundreds of rooms of papyrus scrolls alongside lecture halls and gardens. Seriously damaged in the Herulian invasion of 267, its scholarly function never fully recovered. The site is now an archaeological ruin in central Athens.", src: ["polastron","list"] },
  /* 010 */ /* 010 */ { name: "Library of Antioch", location: "Antioch, Roman Syria", year: 364, cause: "religion", lat: 36.2, lon: 36.16, perp: "Emperor Jovian", desc: "Emperor Jovian ordered the destruction of Antioch's great library, which Julian the Apostate had richly stocked with philosophical and scientific works from across the ancient world. An ideological purge disguised as administrative action.", src: ["ovenden","list"] },
  /* 011 */ /* 011 */ { name: "Library of the Serapeum", location: "Alexandria, Egypt", year: 392, cause: "religion", lat: 31.18, lon: 29.9, perp: "Bishop Theophilus of Alexandria", desc: "The daughter library of Alexandria, housed in the Temple of Serapis, was destroyed when Bishop Theophilus converted the pagan temple to a church. What remained of ancient Alexandrian scholarship was extinguished in the name of the new faith — a theological coup dressed as renovation.", src: ["alexandria","list"] },
  /* 012 */ { name: "Theological Library of Caesarea Maritima", location: "Caesarea Maritima, Palaestina Prima", year: 639, cause: "war", lat: 32.5, lon: 34.89, perp: "Muslim conquest of Caesarea", isNew: true, desc: "Founded by Origen and expanded by Pamphilus, this was among the great Christian libraries of late antiquity, holding perhaps 30,000 volumes including Origen's Hexapla. Both Jerome and Eusebius worked from it. The building was destroyed during the Islamic conquest of Caesarea in 639-640, and with it one of the principal scholarly collections of the early Church.", src: ["caesarea","list"] },
  /* 013 */ /* 012 */ { name: "Library of York (Eboracum)", location: "York, England", year: 867, cause: "war", lat: 53.96, lon: -1.08, perp: "Viking Great Heathen Army", isNew: true, desc: "York was the greatest centre of learning in 8th-century Europe, its library assembled by the scholar Alcuin — tutor to Charlemagne and a key architect of the Carolingian Renaissance. The Viking Great Heathen Army's sack in 867 AD effectively ended York's role as a European intellectual hub. Alcuin had already left for France; what remained was lost. Alcuin had catalogued the collection in a poem naming over 200 authors and carried many of the best volumes to Charlemagne's court in 782, seeding the libraries of Frankish Europe before the Vikings took the rest.", src: ["polastron","list"] },
  /* 014 */ /* 013 */ { name: "Library of al-Hakam II", location: "Cordoba, Al-Andalus", year: 976, cause: "religion", lat: 37.88, lon: -4.78, perp: "Al-Mansur & conservative scholars", desc: "Caliph al-Hakam II assembled 400,000 volumes — the largest library in 10th-century Europe. After his death, regent Al-Mansur burned all books on philosophy and ancient science to curry favor with conservative clerics. The greatest library of medieval Europe destroyed by its own government.", src: ["ovenden","list"] },
  /* 015 */ /* 014 */ { name: "Library of Rayy", location: "Rayy, Buyid Emirate", year: 1029, cause: "religion", lat: 35.6, lon: 51.44, perp: "Sultan Mahmud of Ghazni", desc: "Sultan Mahmud conquered Rayy and ordered the burning of its library, destroying all books he deemed heretical. The Buyid Emirate had been a great patron of philosophy and science; this purge targeted precisely those achievements.", src: ["ovenden","list"] },
  /* 016 */ /* 015 */ { name: "Library at Sazava Monastery", location: "Sazava, Holy Roman Empire", year: 1097, cause: "religion", lat: 49.87, lon: 14.9, perp: "Abbot Diethard", desc: "After the Slavonic Benedictines were expelled from Sazava Monastery, the new Latin-rite abbot Diethard ordered the destruction of Slavonic books and manuscripts collected there for decades. The loss eliminated the primary repository of Old Church Slavonic literary culture in Bohemia.", src: ["ovenden","list"] },
  /* 017 */ /* 016 */ { name: "Library of Banu Ammar (Dar al-Ilm)", location: "Tripoli, Fatimid Caliphate", year: 1109, cause: "war", lat: 34.43, lon: 35.85, perp: "Crusaders under Baldwin I", desc: "Medieval chroniclers credited the library with up to three million volumes. The figure comes from later Arabic sources and is almost certainly inflated, but every account agrees the collection was among the largest in the Islamic world. When Crusaders took the city it reportedly took days to burn. Muslim sources say soldiers used manuscripts as toilet paper before burning them. Contemporaries described it as a catastrophe without precedent. Muslim chroniclers wrote that scholars wept as manuscripts were fed to the flames over several days.", src: ["polastron","list"] },
  /* 018 */ /* 017 */ { name: "Library of Ghazna", location: "Ghazna, Ghurid Empire", year: 1151, cause: "war", lat: 33.55, lon: 68.42, perp: "Ala al-Din Husayn", desc: "The city of Ghazna was sacked and burned for seven days as revenge for the killing of two brothers. Libraries and palaces built by the Ghaznavid dynasty — the dynasty that had produced the great scholar Al-Biruni — were destroyed in the prolonged act of retribution.", src: ["polastron","list"] },
  /* 019 */ /* 018 */ { name: "Library of Nishapur", location: "Nishapur, Seljuk Empire", year: 1154, cause: "war", lat: 36.21, lon: 58.8, perp: "Oghuz Turks", desc: "Nishapur, birthplace of Omar Khayyam and one of the great intellectual cities of the Islamic world, was partially destroyed during the collapse of the Seljuk Empire. Its libraries — at least thirteen institutions that had made it a centre of learning along the Silk Road — were sacked and burned.", src: ["polastron","list"] },
  /* 020 */ /* 019 */ { name: "Library of the Church of Jacob Mar", location: "Nisibis, Zengid State", year: 1171, cause: "war", lat: 37.06, lon: 41.22, perp: "Nur al-Din Zengi", desc: "The church and its library of 1,000 volumes were looted and destroyed by forces under Nur al-Din Zengi. Nisibis had been a significant centre of Syriac Christian scholarship since late antiquity; this destruction extinguished the last remnants of that tradition in the region.", src: ["polastron","list"] },
  /* 021 */ /* 020 */ { name: "Nalanda University Library", location: "Bihar, India", year: 1193, cause: "war", lat: 25.14, lon: 85.44, perp: "Bakhtiyar Khilji", desc: "The greatest repository of Buddhist scholarship in history — a university accumulating knowledge for 700 years. Persian chronicler Minhaj-i-Siraj wrote that the library burned for months, though he was writing decades later and from hearsay. A surviving monk said the soldiers asked what the burning buildings were, and by the time anyone could explain, it was too late.", src: ["polastron","list"] },
  /* 022 */ /* 021 */ { name: "Libraries of Constantinople (Fourth Crusade)", location: "Constantinople, Byzantine Empire", year: 1204, cause: "war", lat: 41.01, lon: 28.98, perp: "Fourth Crusade", desc: "Christian crusaders sacked the Christian capital, scattering a library that preserved classical Greek texts unknown in Western Europe. Works of Aristotle, Plato, and ancient drama were lost or scattered by soldiers who could not read them.", src: ["polastron","list"] },
  /* 023 */ /* 022 */ { name: "Imperial Library of Constantinople", location: "Constantinople, Byzantine Empire", year: 1204, cause: "war", lat: 41.015, lon: 28.975, perp: "Disputed — Fourth Crusade / Ottoman conquest", desc: "Founded in the 4th century and holding over 100,000 volumes at its height, the Imperial Library outlasted the libraries of Alexandria and Pergamon only to meet a disputed end. Scholars debate whether it was destroyed in the Crusader sack of 1204, during the Ottoman conquest of 1453, or lost to fires over centuries.", src: ["polastron","list"] },
  /* 024 */ /* 023 */ { name: "Alamut Castle Library", location: "Alamut, Persia", year: 1256, cause: "war", lat: 36.45, lon: 50.57, perp: "Mongols under Hulagu Khan", rescued: true, desc: "The Nizari Ismaili mountain fortress held a legendary library of astronomical and philosophical texts. Astronomer Nasir al-Din al-Tusi rescued some manuscripts before the Mongols arrived. What he saved quietly influenced European science for centuries.", src: ["polastron","list"] },
  /* 025 */ /* 024 */ { name: "House of Wisdom", location: "Baghdad, Iraq", year: 1258, cause: "war", lat: 33.34, lon: 44.4, perp: "Mongols under Hulagu Khan", desc: "The intellectual capital of the Islamic Golden Age. Chroniclers wrote that the Tigris ran black with ink and red with blood — an image repeated for centuries, though it comes from narrative accounts rather than any count of what was held. The sack was devastating and real. Modern scholarship is more cautious than the legend: Islamic intellectual life continued elsewhere, notably at Maragha, where al-Tusi built an observatory within years.", src: ["polastron","list"] },
  /* 026 */ /* 025 */ { name: "Libraries of Constantinople (Ottoman Conquest)", location: "Constantinople, Byzantine Empire", year: 1453, cause: "war", lat: 41.02, lon: 28.96, perp: "Ottoman Turks", rescued: true, desc: "The final fall of Constantinople scattered what survived of Byzantine scholarship. Fleeing scholars, carrying whatever texts they could, inadvertently seeded the Italian Renaissance — the destruction of one civilization sparking the birth of another.", src: ["polastron","list"] },
  /* 027 */ /* 026 */ { name: "Madrassah Library of Granada", location: "Granada, Spain", year: 1499, cause: "religion", lat: 37.18, lon: -3.6, perp: "Cardinal Cisneros", desc: "80,000 Arabic manuscripts burned in Granada's central square as part of forced Christianization. Poetry, philosophy, history, astronomy — ash by morning. Cisneros later wrote admiringly about Arab learning, apparently without irony.", src: ["ovenden","list"] },
  /* 028 */ /* 027 */ { name: "Bibliotheca Corviniana", location: "Buda, Hungary", year: 1526, cause: "war", lat: 47.5, lon: 19.04, perp: "Ottoman Turks", desc: "King Matthias Corvinus assembled what was considered the second greatest library in Europe after the Vatican — over 2,000 illuminated manuscripts. When the Ottomans defeated Hungary at Mohacs in 1526, the library was looted and scattered. Some manuscripts ended up in Istanbul; others disappeared entirely. What survived became treasures in museums across three continents. Scholars spent centuries afterwards tracking down surviving volumes scattered across European collections.", src: ["list"] },
  /* 029 */ /* 028 */ { name: "English Monastic Libraries", location: "England", year: 1535, cause: "govt", lat: 52.5, lon: -1.5, perp: "Royal officials under Henry VIII", approx: true, desc: "The Dissolution of the Monasteries scattered and destroyed centuries of medieval scholarship. Manuscripts were used as wastepaper, bookbinders' material, and kindling. One visitor described monastery books being used to scrub candlesticks. An entire literary heritage decimated in a decade for political and economic gain.", src: ["knuth","civallero","list"] },
  /* 030 */ /* 029 */ { name: "Glasney College Library", location: "Penryn, Cornwall", year: 1548, cause: "govt", lat: 50.16, lon: -5.1, perp: "Royal officials under Edward VI", desc: "The destruction of Glasney College erased the only institutional repository of the Cornish literary tradition. The Cornish language's near-extinction began here, with a pile of burning manuscripts.", src: ["knuth","civallero","list"] },
  /* 031 */ /* 030 */ { name: "Records on Gozo", location: "Gozo, Hospitaller Malta", year: 1551, cause: "war", lat: 36.04, lon: 14.24, perp: "Ottoman Turks", desc: "Most paper records held on Gozo were lost during an Ottoman raid in 1551. The raid depopulated much of the island, and the administrative and historical records that documented Gozo's medieval history were either taken or burned. An entire chapter of Maltese documentary history erased in a single raid.", src: ["gozo","list"] },
  /* 032 */ /* 031 */ { name: "Maya Codices of the Yucatan", location: "Mani, Mexico", year: 1562, cause: "religion", lat: 20.39, lon: -89.56, perp: "Bishop Diego de Landa", desc: "De Landa burned virtually the entire written record of Maya civilization in a single auto-da-fe. Only 4 Maya codices survive today. He later wrote a book about Maya culture using oral knowledge from survivors — a record of the civilization whose written memory he himself destroyed.", src: ["ovenden","list"] },
  /* 033 */ /* 032 */ { name: "Raglan Castle Library", location: "Raglan, Wales", year: 1646, cause: "war", lat: 51.77, lon: -2.87, perp: "Parliamentary Army", desc: "The Earl of Worcester's library was burned during the English Civil War — not as military necessity but as cultural contempt for the Royalist aristocracy. The books were a proxy for the men who owned them.", src: ["list"] },
  /* 034 */ /* 033 */ { name: "Swedish National Library, Tre Kronor", location: "Stockholm, Sweden", year: 1697, cause: "fire", lat: 59.33, lon: 18.07, perp: "Accidental fire", desc: "The Tre Kronor castle fire of 1697 destroyed the Swedish National Library and Royal Archives housed within it. Centuries of Swedish royal records, medieval manuscripts, and the accumulated archives of the Vasa dynasty were lost. The fire began in a chimney and spread so rapidly that little could be saved.", src: ["list"] },
  /* 035 */ /* 034 */ { name: "University of Copenhagen Library", location: "Copenhagen, Denmark", year: 1728, cause: "fire", lat: 55.68, lon: 12.57, perp: "Copenhagen Fire of 1728", desc: "The great fire that devastated central Copenhagen in 1728 consumed the University Library, one of Scandinavia's most important scholarly collections. Thousands of volumes of Nordic history, theology, and natural philosophy — including irreplaceable manuscripts of Old Norse literature — were lost in the catastrophic blaze.", src: ["list"] },
  /* 036 */ /* 035 */ { name: "Cotton Library, London", location: "London, UK", year: 1731, cause: "fire", lat: 51.5, lon: -0.13, perp: "Accidental fire at Ashburnham House", desc: "The Cotton Library, assembled by antiquary Robert Cotton and containing irreplaceable Anglo-Saxon manuscripts including Beowulf and two copies of Magna Carta, was severely damaged by fire at Ashburnham House in 1731. Around a quarter of the collection was destroyed or badly damaged. Many manuscripts crumbled to fragments that scholars spent centuries painstakingly reconstructing.", src: ["list"] },
  /* 037 */ /* 036 */ { name: "Royal Library of Portugal, Lisbon", location: "Lisbon, Portugal", year: 1755, cause: "fire", lat: 38.71, lon: -9.14, perp: "Great Lisbon Earthquake and fire", desc: "The catastrophic Lisbon earthquake of 1755 triggered a tsunami and fires that burned for six days. The Royal Library in the Palace of Ribeira, holding 70,000 volumes including the only surviving records of Vasco da Gama's original voyages, was completely destroyed. The historical records of the Age of Discovery were lost in an afternoon of geological violence. Among the losses were the only surviving logs and charts from Vasco da Gama's voyages and the early Portuguese explorations, primary records of the Age of Discovery that cannot be reconstructed.", src: ["list"] },
  /* 038 */ /* 037 */ { name: "Zaluski Library", location: "Warsaw, Poland", year: 1794, cause: "war", lat: 52.23, lon: 21.01, perp: "Imperial Russian Army / Nazi German troops", desc: "One of Europe's first public libraries — 400,000 volumes. Russian forces carried off 262,000 volumes after the Kosciuszko Uprising of 1794. What remained was destroyed again by the Nazis in 1944. One library, two total destructions, 150 years apart.", src: ["zaluski","list"] },
  /* 039 */ /* 038 */ { name: "Library of Congress (1814)", location: "Washington D.C., USA", year: 1814, cause: "war", lat: 38.89, lon: -77, perp: "British Army", desc: "British forces burned the Capitol and its fledgling library during the War of 1812. Thomas Jefferson offered his personal collection of 6,487 books as a replacement — so philosophical and eclectic that some congressmen tried to reject it as too radical. His library became the seed of the modern LOC.", src: ["loc","list"] },
  /* 040 */ /* 039 */ { name: "Several Libraries, Mexico", location: "Mexico City & major cities, Mexico", year: 1856, cause: "war", lat: 19.43, lon: -99.13, perp: "Liberal troops & anti-clericalists", approx: true, desc: "During and after the Mexican Reform War, liberal governments permitted or carried out the dispersal of numerous ecclesiastical libraries. Church collections accumulated over three centuries of colonial rule were broken up, sold off, or burned as part of anti-clerical reform policies.", src: ["list"] },
  /* 041 */ /* 040 */ { name: "Mughal Imperial Library, Delhi", location: "Delhi, India", year: 1857, cause: "war", lat: 28.65, lon: 77.23, perp: "British forces (Indian Rebellion)", isNew: true, desc: "The Mughal court's library represented centuries of accumulated scholarship — Persian manuscripts, Sanskrit translations, illuminated Qurans, works of Mughal art and science. When British forces entered Delhi following the suppression of the 1857 rebellion, the library was looted or destroyed. The last great repository of Mughal intellectual culture was dispersed in an afternoon.", src: ["list"] },
  /* 042 */ /* 041 */ { name: "University of Alabama Library", location: "Tuscaloosa, Alabama, USA", year: 1865, cause: "war", lat: 33.21, lon: -87.54, perp: "Union Army troops", desc: "During the Civil War, Union troops destroyed most buildings on the University of Alabama campus including the library. According to legend, only one book survived — an English translation of the Quran that a soldier chose to pocket rather than burn.", src: ["list"] },
  /* 043 */ /* 042 */ { name: "Mosque-Library of Turnovo", location: "Turnovo, Bulgaria", year: 1877, cause: "war", lat: 43.07, lon: 25.62, perp: "Christian Bulgarian forces", desc: "During the Russo-Turkish War and Bulgaria's liberation, a mosque containing a library of Turkish and Ottoman texts was burned. The books were destroyed alongside the mosque as a symbolic act of the religious and political transformation sweeping the region.", src: ["list"] },
  /* 044 */ /* 043 */ { name: "Birmingham Central Library", location: "Birmingham, UK", year: 1879, cause: "fire", lat: 52.48, lon: -1.9, perp: "Accidental fire during building works", desc: "A fire broke out behind a wooden partition serving as a temporary wall during building renovations in January 1879, destroying much of the Birmingham Central Library's collection. Thousands of volumes of local history, rare books, and reference works were lost before the fire could be contained.", src: ["list"] },
  /* 045 */ /* 044 */ { name: "Royal Library of Burma", location: "Mandalay Palace, Burma", year: 1885, cause: "war", lat: 21.96, lon: 96.08, perp: "British Army", desc: "British troops looted the royal palace at the end of the Third Anglo-Burmese War, dispersing the royal library's parabaik manuscripts — hand-painted books recording Burmese history, religion, and art. Much ended up in British museums, where portions remain today.", src: ["list"] },
  /* 046 */ /* 045 */ { name: "University of Virginia Library", location: "Charlottesville, Virginia, USA", year: 1895, cause: "fire", lat: 38.03, lon: -78.5, perp: "Accidental fire", desc: "The University of Virginia Library, housed in the Rotunda designed by Thomas Jefferson, was severely damaged by fire in October 1895. The fire destroyed the Annex and damaged Jefferson's original Rotunda building. Thousands of irreplaceable books and manuscripts, including early Americana, were lost in the blaze.", src: ["list"] },
  /* 047 */ /* 046 */ { name: "Hanlin Academy Library", location: "Beijing, China", year: 1900, cause: "war", lat: 39.91, lon: 116.39, perp: "Boxer Uprising / disputed", desc: "China's oldest and most prestigious literary institution burned during the Boxer Uprising. Western diplomats in the nearby Legation Quarter reportedly watched it burn, unwilling to risk soldiers to save Chinese books. The Academy held an encyclopedia of over 11,000 volumes covering centuries of Chinese history.", src: ["unesco_lost","list"] },
  /* 048 */ /* 047 */ { name: "New York State Library", location: "Albany, New York, USA", year: 1911, cause: "fire", lat: 42.65, lon: -73.75, perp: "Capitol building fire", desc: "A fire in the New York State Capitol building in March 1911 destroyed the State Library, one of the most important research collections in America. Around 450,000 books and thousands of manuscripts were destroyed, including irreplaceable records of early American history and the complete collection of manuscripts once owned by Benjamin Franklin.", src: ["unesco_lost","list"] },
  /* 049 */ /* 048 */ { name: "Catholic University of Leuven", location: "Leuven, Belgium", year: 1914, cause: "war", lat: 50.88, lon: 4.7, perp: "German Occupation Forces", desc: "German troops systematically burned the medieval library as collective punishment. 300,000 volumes including irreplaceable medieval manuscripts were destroyed. Rebuilt with international donations — then burned again by Germany in 1940. The same country, the same library, twice in 26 years.", src: ["unesco_lost","list"] },
  /* 050 */ /* 049 */ { name: "Public Records Office of Ireland", location: "Dublin, Ireland", year: 1922, cause: "war", lat: 53.35, lon: -6.27, perp: "Anti-Treaty IRA / Irish Civil War", desc: "The Four Courts complex held Ireland's primary archive going back to medieval times. An explosion during the Civil War destroyed 1,000 years of Irish legal and genealogical records. The paper memory of a nation, gone in an instant.", src: ["unesco_lost","list"] },
  /* 051 */ /* 050 */ { name: "University of Tokyo Library", location: "Tokyo, Japan", year: 1923, cause: "fire", lat: 35.71, lon: 139.76, perp: "Great Kanto Earthquake and fire", desc: "The catastrophic Great Kanto Earthquake of 1923 and the firestorms that followed destroyed the University of Tokyo Library. The collection included the Max Muller Library of South Asian texts and the Nishimura collection of rare Japanese historical documents — irreplaceable primary sources for Asian studies.", src: ["raven","list"] },
  /* 052 */ /* 051 */ { name: "Several Religious Libraries, Madrid", location: "Madrid, Republican Spain", year: 1931, cause: "war", lat: 40.42, lon: -3.7, perp: "Anarchists & anti-clericalists", desc: "In 1931, radical leftists burned several churches and their associated libraries across Madrid. Ecclesiastical collections accumulated over centuries were destroyed in a wave of anti-clerical violence that foreshadowed the coming civil war.", src: ["unesco_lost","list"] },
  /* 053 */ /* 052 */ { name: "National Library of Nicaragua", location: "Nicaragua", year: 1931, cause: "fire", lat: 12.14, lon: -86.28, perp: "1931 Managua earthquake and fire", desc: "The National Library of Nicaragua was damaged in the catastrophic 1931 Managua earthquake and the fires that followed. A second earthquake in 1972 caused further damage. The repeated natural disasters left the national library's collection severely depleted, representing a significant loss of Nicaraguan historical and literary heritage.", src: ["unesco_lost","list"] },
  /* 054 */ /* 053 */ { name: "Oriental Library, Shanghai", location: "Shanghai, China", year: 1932, cause: "war", lat: 31.23, lon: 121.47, perp: "Imperial Japanese Army", desc: "Japanese forces deliberately burned the Oriental Library — 450,000 volumes including rare Song dynasty texts. One of China's largest libraries, its destruction was recognized internationally as a deliberate cultural atrocity.", src: ["unesco_lost","list"] },
  /* 055 */ /* 054 */ { name: "Institut fuer Sexualwissenschaft", location: "Berlin, Germany", year: 1933, cause: "govt", lat: 52.52, lon: 13.38, perp: "Deutsche Studentenschaft / Nazi regime", desc: "Magnus Hirschfeld's pioneering institute — holding the world's most comprehensive research on gender and sexuality — was ransacked and burned. The footage became the defining image of Nazi censorship. It set LGBTQ+ scholarship back by decades.", src: ["unesco_lost","list"] },
  /* 056 */ /* 055 */ { name: "University of Oviedo Library", location: "Oviedo, Spain", year: 1934, cause: "war", lat: 43.36, lon: -5.85, perp: "Revolutionaries / disputed", desc: "During the Asturian miners' strike of 1934, the University of Oviedo was caught between revolutionary miners and government forces. The library, containing collections of regional history and medieval Asturian manuscripts, was badly damaged in the crossfire.", src: ["unesco_lost","list"] },
  /* 057 */ /* 056 */ { name: "Chinese University Libraries (WWII)", location: "Multiple cities, China", year: 1937, cause: "war", lat: 30, lon: 114, perp: "Imperial Japanese Army", approx: true, desc: "During the Second Sino-Japanese War, Japanese forces destroyed or severely damaged the libraries of National Tsing Hua University, Nankai University, and numerous other institutions. The systematic destruction of Chinese intellectual infrastructure was deliberate policy.", src: ["unesco_lost","list"] },
  /* 058 */ /* 057 */ { name: "National Library of Serbia", location: "Belgrade, Yugoslavia", year: 1941, cause: "war", lat: 44.82, lon: 20.46, perp: "Nazi German Luftwaffe", desc: "Bombed on Hitler's direct orders on Easter Sunday, 1941. The library held the largest collection of Serbian medieval manuscripts. Over 350,000 books incinerated overnight. The Nazis understood that destroying records is a form of destroying a people.", src: ["unesco_lost","list"] },
  /* 059 */ /* 058 */ { name: "SS. Cyril and Methodius National Library", location: "Sofia, Bulgaria", year: 1943, cause: "war", lat: 42.7, lon: 23.32, perp: "Allied air forces", desc: "The national library sustained severe damage during Allied bombing raids in 1943-1944. Among the significant cultural casualties: rare Bulgarian manuscripts and Ottoman-era documents irreplaceable to Balkan history.", src: ["unesco_lost","list"] },
  /* 060 */ /* 059 */ { name: "National Library of Peru", location: "Lima, Peru", year: 1943, cause: "fire", lat: -12.06, lon: -77.04, perp: "Accidental fire", desc: "The National Library of Peru, founded by independence hero Jose de San Martin in 1821, was severely damaged by fire in May 1943. Thousands of colonial-era manuscripts, rare books, and historical documents tracing Peru's history from pre-Columbian times through independence were destroyed. The loss was considered a national catastrophe.", src: ["unesco_lost","list"] },
  /* 061 */ /* 060 */ { name: "Krasinski Library, Warsaw", location: "Warsaw, Poland", year: 1944, cause: "govt", lat: 52.25, lon: 21, perp: "Nazi German troops", desc: "After suppressing the Warsaw Uprising, Nazi troops burned Warsaw library by library — a systematic campaign to erase Polish cultural identity. Over a million volumes from the National Library's special collections destroyed.", src: ["unesco_lost","list"] },
  /* 062 */ /* 061 */ { name: "Library of the Zamoyski Family", location: "Warsaw, Poland", year: 1944, cause: "govt", lat: 52.24, lon: 21.01, perp: "Nazi German troops", desc: "The Zamoyski Family library housed the collections of the former Zamoyski Academy and was one of Poland's great private scholarly libraries. Deliberately set ablaze by Nazi troops in the aftermath of the Warsaw Uprising.", src: ["unesco_lost","list"] },
  /* 063 */ /* 062 */ { name: "Central Archives of Historical Records", location: "Warsaw, Poland", year: 1944, cause: "govt", lat: 52.245, lon: 21.015, perp: "Nazi German troops", desc: "Nazi troops systematically burned the Central Archives after the Warsaw Uprising. They held centuries of Polish administrative, legal, and historical records. Their destruction was deliberate policy — the erasure of the documentary basis of Polish statehood.", src: ["unesco_lost","list"] },
  /* 064 */ /* 063 */ { name: "Private Libraries of Tokyo", location: "Tokyo, Japan", year: 1945, cause: "war", lat: 35.69, lon: 139.69, perp: "US Army Air Force firebombing", approx: true, desc: "US firebombing of Tokyo in 1945 consumed vast swathes of the city, destroying many private Japanese libraries and local collections. The raids eliminated irreplaceable collections of Japanese literature, family records, and local history.", src: ["raven","unesco_lost","list"] },
  /* 065 */ /* 064 */ { name: "Warsaw Public Library", location: "Warsaw, Poland", year: 1945, cause: "govt", lat: 52.23, lon: 21.03, perp: "Nazi German troops", desc: "Before World War II the library contained 500,000 books. By 1945, after systematic Nazi destruction during and after the Warsaw Uprising, it was reduced to rubble — part of the broader plan to permanently eliminate Polish cultural identity.", src: ["unesco_lost","list"] },
  /* 066 */ /* 065 */ { name: "Raczynski Library, Poznan", location: "Poznan, Poland", year: 1945, cause: "govt", lat: 52.41, lon: 16.93, perp: "Nazi German troops", desc: "Retreating Nazi troops planted explosives in the building and detonated them, destroying much of this important Polish library. The Raczynski had survived the earlier occupation largely intact, making its deliberate destruction in the final days of war a particularly calculated act.", src: ["unesco_lost","list"] },
  /* 067 */ /* 066 */ { name: "Jewish Theological Seminary Library", location: "New York City, USA", year: 1966, cause: "fire", lat: 40.81, lon: -73.96, perp: "Accidental fire", desc: "A fire in April 1966 at the Jewish Theological Seminary of America destroyed or severely damaged thousands of volumes from one of the world's most important collections of Judaica. Rare Hebrew manuscripts, incunabula, and irreplaceable documents of Jewish intellectual and religious history were among the losses.", src: ["unesco_lost","list"] },
  /* 068 */ /* 067 */ { name: "Lebanese National Library", location: "Beirut, Lebanon", year: 1975, cause: "war", lat: 33.89, lon: 35.5, perp: "Lebanese Civil War", desc: "Caught in the downtown front lines, shelled to a shell. 200,000 volumes destroyed including much of Lebanon's Ottoman-era historical record. The roofless building stood for 25 years before partial restoration.", src: ["unesco_lost","list"] },
  /* 069 */ /* 068 */ { name: "National Library of Cambodia", location: "Phnom Penh, Cambodia", year: 1976, cause: "govt", lat: 11.57, lon: 104.93, perp: "Khmer Rouge", desc: "The Khmer Rouge burned most collections and converted the building into a pigsty. Only 20% of materials survived. Year Zero ideology targeted libraries as the physical embodiment of a past the regime needed to abolish.", src: ["unesco_lost","list"] },
  /* 070 */ /* 069 */ { name: "Jaffna Public Library", location: "Jaffna, Sri Lanka", year: 1981, cause: "war", lat: 9.66, lon: 80.01, perp: "Government-aligned mob and police", desc: "One of Asia's largest libraries — 97,000 volumes including irreplaceable Tamil manuscripts. Its burning is still cited as the moment the Sri Lankan civil war became inevitable: a cultural assassination that made political resolution impossible.", src: ["jaffna","knuth","list"] },
  /* 071 */ { name: "Charles A. Halbert Public Library", location: "Basseterre, Saint Kitts and Nevis", year: 1982, cause: "fire", lat: 17.3, lon: -62.72, perp: "Fire", isNew: true, desc: "The public library of Saint Kitts was destroyed by fire in 1982. Small island collections rarely hold duplicates of local material, so the loss of a national public library falls disproportionately hard: what burns is often the only copy anywhere.", src: ["halbert","list"] },
  /* 072 */ { name: "St Michael's House", location: "Crafers, South Australia", year: 1983, cause: "fire", lat: -35.0, lon: 138.7, perp: "Ash Wednesday bushfires", isNew: true, desc: "St Michael's House was destroyed in the Ash Wednesday bushfires of February 1983, among the deadliest fire days in Australian history. Its entire library of 40,000 volumes was lost, including works dating to the 16th century.", src: ["trove_sms","list"] },
  /* 073 */ /* 070 */ { name: "Sikh Reference Library", location: "Punjab, India", year: 1984, cause: "war", lat: 31.62, lon: 74.88, perp: "Indian Army (Operation Blue Star)", desc: "During the storming of the Golden Temple complex, the Reference Library — holding rare Sikh manuscripts going back centuries — was looted. The Indian government denied it for years. Much has never been returned.", src: ["sikh","list"] },
  /* 074 */ /* 071 */ { name: "Dalhousie University Law Library", location: "Halifax, Nova Scotia, Canada", year: 1985, cause: "fire", lat: 44.63, lon: -63.59, perp: "Lightning strike (electrical)", desc: "A lightning strike in August 1985 caused a short circuit that started a fire at the Dalhousie University Law Library. The fire destroyed significant portions of the legal collection, including rare Canadian legal texts and historical case records. It remains one of the most significant accidental library losses in Canadian history.", src: ["unesco_lost","list"] },
  /* 075 */ /* 072 */ { name: "Los Angeles Central Library", location: "Los Angeles, California, USA", year: 1986, cause: "fire", lat: 34.05, lon: -118.26, perp: "Arson (suspected)", rescued: true, desc: "Two fires in 1986 — the second while the building was under repair from the first — destroyed or damaged around 400,000 books at the Los Angeles Central Library. The first fire in April was one of the largest library fires in US history. A massive volunteer effort helped salvage and restore portions of the collection over subsequent years.", src: ["lapl","list"] },
  /* 076 */ /* 073 */ { name: "Academy of Sciences Library, Leningrad", location: "Leningrad, USSR", year: 1988, cause: "fire", lat: 59.94, lon: 30.3, perp: "Accidental fire", desc: "A fire in February 1988 at the Library of the USSR Academy of Sciences in Leningrad damaged around 400,000 volumes and destroyed approximately 4,000 rare manuscripts. The library, one of the oldest and largest in Russia, had survived the Siege of Leningrad during World War II only to fall victim to an accidental fire during renovation work.", src: ["abbey","list"] },
  /* 077 */ /* 074 */ { name: "Central University Library of Bucharest", location: "Bucharest, Romania", year: 1989, cause: "war", lat: 44.43, lon: 26.1, perp: "Romanian Land Forces", desc: "Set on fire during the Romanian Revolution in December 1989 amid fighting that accompanied the fall of Ceausescu's regime. Hundreds of thousands of volumes were destroyed, including irreplaceable Romanian historical documents accumulated over more than a century.", src: ["unesco_lost","list"] },
  /* 078 */ /* 075 */ { name: "Oriental Institute, Sarajevo", location: "Sarajevo, Bosnia", year: 1992, cause: "war", lat: 43.86, lon: 18.41, perp: "Bosnian Serb Army", desc: "Held the world's largest collection of Islamic manuscripts in the Balkans — 5,263 manuscripts spanning Ottoman history. Destroyed by deliberate shelling as part of a systematic campaign of cultural genocide.", src: ["riedlmayer_erasing","riedlmayer_crimes","list"] },
  /* 079 */ /* 076 */ { name: "National Library of Bosnia and Herzegovina", location: "Sarajevo, Bosnia", year: 1992, cause: "war", lat: 43.85, lon: 18.42, perp: "Bosnian Serb Army", rescued: true, desc: "Over 2 million books. Deliberately shelled for three days until it collapsed in flames. Citizens formed human chains under sniper fire to rescue books. Librarian Aida Buturovc was killed doing so.", src: ["riedlmayer_crimes","harvard","nub"] },
  /* 080 */ /* 077 */ { name: "Abkhazian Research Institute Library", location: "Sukhumi, Abkhazia", year: 1992, cause: "war", lat: 43, lon: 41.02, perp: "Georgian Armed Forces", desc: "The Abkhazian Research Institute and National Library were destroyed during the War in Abkhazia in October 1992. The destruction eliminated the primary repository of Abkhazian cultural heritage, including unique manuscripts documenting the history and language of the Abkhaz people.", src: ["unesco_lost","list"] },
  /* 081 */ /* 078 */ { name: "Norwich Central Library", location: "Norwich, England, UK", year: 1994, cause: "fire", lat: 52.63, lon: 1.3, perp: "Electrical fault (accidental)", desc: "Norwich Central Library caught fire in August 1994 due to an electrical fault, destroying the building and most of its contents. Thousands of books, local history archives, and reference collections were lost. The library had served the community for decades and its rebuilding became a symbol of civic renewal.", src: ["bbc_norwich","list"] },
  /* 082 */ /* 079 */ { name: "City Library, Linkoping", location: "Linkoping, Sweden", year: 1996, cause: "fire", lat: 58.41, lon: 15.62, perp: "Arson (perpetrator unidentified)", desc: "After a year of repeated arson attempts against an LGBTQ+ information bureau operating from the building, the Linkoping city library was burned down in September 1996. No one was ever convicted, making it one of Sweden's most significant unsolved cultural attacks.", src: ["unesco_lost","list"] },
  /* 083 */ /* 080 */ { name: "Pol-i-Khomri Public Library", location: "Pol-i-Khomri, Afghanistan", year: 1998, cause: "religion", lat: 35.95, lon: 68.71, perp: "Taliban", desc: "55,000 books and manuscripts. Burned as part of the Taliban's systematic destruction of secular knowledge across Afghanistan. This destruction received almost no international coverage at the time.", src: ["unesco_lost","list"] },
  /* 084 */ /* 081 */ { name: "Iraq National Library and Archive", location: "Baghdad, Iraq", year: 2003, cause: "war", lat: 33.34, lon: 44.39, perp: "Looters amid US invasion", desc: "In the chaos of the 2003 invasion, the National Library was looted and burned. Cuneiform tablets, Ottoman manuscripts, and 450,000 books were lost. US forces had been warned in advance by scholars but failed to protect cultural sites.", src: ["bbc_iraq","list"] },
  /* 085 */ /* 082 */ { name: "Libraries Damaged in 2004 Indian Ocean Tsunami", location: "Indonesia, Malaysia, Maldives, Thailand, Sri Lanka", year: 2004, cause: "fire", lat: 3.32, lon: 95.85, perp: "2004 Indian Ocean earthquake and tsunami", approx: true, desc: "The catastrophic 2004 Indian Ocean earthquake and tsunami caused widespread damage to libraries, archives, and museums across multiple countries. Local libraries, school collections, and municipal archives were swept away or inundated across coastal communities in Indonesia, Thailand, Sri Lanka, and the Maldives, destroying records of local history, culture, and community life.", src: ["list"] },
  /* 086 */ /* 083 */ { name: "Duchess Anna Amalia Library", location: "Weimar, Germany", year: 2004, cause: "fire", lat: 50.98, lon: 11.33, perp: "Accidental electrical fault", isNew: true, rescued: true, desc: "Goethe's library — one of the most important repositories of German literary heritage, serving Goethe, Schiller, and Herder — was devastated by an accidental electrical fire in September 2004. Around 50,000 books were destroyed and 35,000 damaged. In a rare hopeful story, volunteers formed a human chain through the night passing burning books to safety. The library was restored and reopened in 2007.", src: ["list"] },
  /* 087 */ /* 084 */ { name: "People's Library, Occupy Wall Street", location: "New York City, USA", year: 2011, cause: "govt", lat: 40.71, lon: -74.01, perp: "NYC Dept. of Sanitation", desc: "The People's Library at Occupy Wall Street had catalogued over 5,500 donated books. When the NYPD cleared Zuccotti Park in November 2011, the library was seized and most books destroyed or rendered unusable. The first significant library destruction on American soil in nearly two centuries. Books were loaded into sanitation trucks and later found damaged at a city facility; a court subsequently found the city liable.", src: ["ows","list"] },
  /* 088 */ /* 085 */ { name: "Egyptian Scientific Institute", location: "Cairo, Egypt", year: 2011, cause: "war", lat: 30.05, lon: 31.25, perp: "Egyptian Revolution street violence", desc: "A fire during the revolution spread to the 200-year-old institute. Of 200,000 volumes, only 30,000 were saved. Among the losses: one of only 21 surviving copies of Napoleon's Description de l'Egypte — irreplaceable.", src: ["elpais_egypt","list"] },
  /* 089 */ /* 086 */ { name: "Ahmed Baba Institute, Timbuktu", location: "Timbuktu, Mali", year: 2013, cause: "religion", lat: 16.77, lon: -3, perp: "Islamist militias (AQIM)", rescued: true, desc: "Retreating militants set fire to the institute in January 2013. Early reports said its whole collection was lost, and headlines worldwide repeated it. The reality was far better: librarian Abdel Kader Haidara and Timbuktu residents had already smuggled the bulk of the manuscripts out in trunks and rice sacks. Of roughly 30,000 held there, an estimated 2,000 burned. The rescue, not the loss, is the story.", src: ["fp_timbuktu","guardian_timbuktu","list"] },
  /* 090 */ /* 087 */ { name: "Ratanda Public Library", location: "Lesedi Municipality, South Africa", year: 2013, cause: "war", lat: -26.48, lon: 28.08, perp: "Public riots", desc: "Burned during public service delivery riots in March 2013. 1,807 books destroyed along with computers and all technological infrastructure. A tragic irony in a community where access to books was already severely limited.", src: ["lor_sa","list"] },
  /* 091 */ /* 088 */ { name: "Fisheries and Oceans Canada Libraries", location: "Canada", year: 2013, cause: "govt", lat: 45.42, lon: -75.7, perp: "Harper Government", approx: true, desc: "Seven of nine Fisheries and Oceans libraries closed and collections discarded to save $443,000 Canadian. Scientists called it data destruction. Research built over 50 years thrown away and irreplaceable.", src: ["tyee","list"] },
  /* 092 */ /* 089 */ { name: "Saeh Library, Tripoli", location: "Tripoli, Lebanon", year: 2014, cause: "religion", lat: 34.44, lon: 35.84, perp: "Unknown (sectarian attack)", desc: "The Christian Saeh Library, containing over 80,000 manuscripts and books, was burned down in January 2014 in a widely condemned sectarian attack. Its founder described standing in the ashes of his life's work. The attack prompted solidarity across all of Lebanon's religious communities.", src: ["naharnet","list"] },
  /* 093 */ /* 090 */ { name: "National Archives of Bosnia (partial)", location: "Sarajevo, Bosnia", year: 2014, cause: "war", lat: 43.855, lon: 18.405, perp: "Bosnian rioters", desc: "During the 2014 unrest in Bosnia, large amounts of historical documents were destroyed when rioters set fire to the National Archives building. The archives contained irreplaceable Ottoman-era records central to the pre-war history of the country.", src: ["bih_court","list"] },
  /* 094 */ /* 091 */ { name: "Mosul University Libraries", location: "Mosul, Iraq", year: 2014, cause: "religion", lat: 36.34, lon: 43.13, perp: "ISIS / ISIL", desc: "Systematic public book burnings across Mosul — the university library, the museum library, and countless private collections. Rare manuscripts and maps going back centuries burned as tools of infidelity and filmed as propaganda.", src: ["guardian_isis","list"] },
  /* 095 */ /* 092 */ { name: "Libraries of Al Anbar Governorate", location: "Al Anbar, Iraq", year: 2014, cause: "religion", lat: 33.42, lon: 43.3, perp: "ISIS / ISIL", approx: true, desc: "ISIS extended its systematic book burning campaign across the Al Anbar Governorate in late 2014, destroying libraries in towns and cities throughout the region. Local collections, school libraries, and private archives accumulated over generations were burned as part of the campaign to obliterate pre-Islamic and non-Salafi knowledge.", src: ["guardian_isis","list"] },
  /* 096 */ /* 093 */ { name: "Glasgow School of Art Library", location: "Glasgow, Scotland, UK", year: 2014, cause: "fire", lat: 55.87, lon: -4.26, perp: "Accidental fire (twice)", desc: "The Mackintosh Library inside Charles Rennie Mackintosh's iconic Glasgow School of Art building was badly damaged by fire in May 2014, and then almost completely destroyed by a second fire in June 2018 while restoration work was underway. The double loss of one of the world's finest examples of Art Nouveau architecture and its library is considered one of the greatest cultural tragedies in modern Scottish history.", src: ["guardian_gsa","guardian_gsa2","list"] },
  /* 097 */ /* 094 */ { name: "INION Library, Moscow", location: "Moscow, Russia", year: 2015, cause: "fire", lat: 55.67, lon: 37.56, perp: "Accidental fire", desc: "The Institute of Scientific Information on Social Sciences held around 14 million items — one of the world's largest social science collections. A fire in January 2015 spread to 2,000 square metres, destroying an estimated 15% of the collection including irreplaceable 18th and 19th-century periodicals.", src: ["qz_inion","list"] },
  /* 098 */ /* 095 */ { name: "Mosul Public Library", location: "Mosul, Iraq", year: 2015, cause: "religion", lat: 36.33, lon: 43.12, perp: "ISIS / ISIL", desc: "The Central Public Library of Ninawa held 8,000 rare books and manuscripts — Syriac and Latin printed books from the 16th and 17th centuries, rare Ottoman newspapers. ISIS publicly burned them in February 2015. What could not be burned was bulldozed.", src: ["guardian_isis","list"] },
  /* 099 */ /* 096 */ { name: "Mzuzu University Library", location: "Mzuzu, Malawi", year: 2015, cause: "fire", lat: -11.46, lon: 34.02, perp: "Accidental fire", rescued: true, desc: "The Mzuzu University Library in Malawi caught fire in the early hours of December 18, 2015, and was completely destroyed. The entire book collection, computer equipment, and institutional archives were lost. For a developing nation with limited resources for rebuilding, the loss represented a severe setback to higher education in northern Malawi.", src: ["scecsal_mzuzu","list"] },
  /* 100 */ /* 097 */ { name: "Howard College Law Library", location: "Durban, South Africa", year: 2016, cause: "war", lat: -29.87, lon: 30.98, perp: "FeesMustFall protestors", desc: "The law library at Howard College, University of KwaZulu-Natal, was burned by protestors during the FeesMustFall movement in September 2016. Early Roman-Dutch law texts and rare legal manuscripts were among the losses — an unintended casualty of a movement fighting for access to education.", src: ["independent_ukzn","lor_sa","list"] },
  /* 101 */ /* 098 */ { name: "National Museum of Brazil Library", location: "Rio de Janeiro, Brazil", year: 2018, cause: "fire", lat: -22.91, lon: -43.22, perp: "Accidental fire (electrical)", desc: "A catastrophic fire on September 2, 2018 destroyed the National Museum of Brazil and its library — the country's oldest and most important natural history museum, founded in 1818. An estimated 20 million items were lost, including priceless indigenous cultural artefacts, palaeontological specimens, and a library of rare manuscripts. Brazil's scientific and cultural heritage was devastated.", src: ["list"] },
  /* 102 */ /* 099 */ { name: "Jagger Library, Cape Town (partial)", location: "Cape Town, South Africa", year: 2021, cause: "fire", lat: -33.96, lon: 18.46, perp: "Table Mountain wildfire", desc: "The 2021 Table Mountain fire partially destroyed the Jagger Library at the University of Cape Town, including the African Studies collection — one of the most important repositories of African history and scholarship on the continent. Thousands of rare books, photographs, and archival materials documenting African history were lost in the fire that swept through the campus.", src: ["ewn_jagger","jagger_abd","list"] },
  /* 103 */ /* 100 */ { name: "Korolenko State Scientific Library", location: "Kharkiv, Ukraine", year: 2022, cause: "war", lat: 49.99, lon: 36.23, perp: "Russian bombardment", isNew: true, desc: "One of Ukraine's largest and oldest research libraries, damaged during the bombardment of Kharkiv. It is among the library sites UNESCO has formally verified as damaged in the war.", src: ["unesco_ua","list"] },
  /* 104 */ /* 101 */ { name: "Central City Library, Mariupol", location: "Mariupol, Ukraine", year: 2022, cause: "war", lat: 47.1, lon: 37.54, perp: "Russian bombardment", isNew: true, desc: "The V.G. Korolenko Central City Library was destroyed during the siege of Mariupol. UNESCO lists it among verified damaged cultural sites.", src: ["unesco_ua","list"] },
  /* 105 */ /* 102 */ { name: "Kherson Regional Scientific Library", location: "Kherson, Ukraine", year: 2022, cause: "war", lat: 46.64, lon: 32.61, perp: "Russian forces", isNew: true, desc: "The Kherson Regional Universal Scientific Library was damaged during the occupation and shelling of the city. A branch of the Kherson Regional State Archive was also damaged, one of five archives on UNESCO's verified list.", src: ["unesco_ua","list"] },
  /* 106 */ /* 103 */ { name: "Ukrainian Libraries (UNESCO-verified)", location: "Ukraine, multiple regions", year: 2022, cause: "war", lat: 49, lon: 32, perp: "Russian armed forces", isNew: true, approx: true, desc: "As of 29 September 2026 UNESCO had verified damage to 563 Ukrainian cultural sites, including 24 libraries and 5 archives, across the Chernihiv, Kharkiv, Donetsk, Luhansk, Kherson, Sumy, Zaporizhzhia, Dnipropetrovsk and Kyiv regions. A regional record covering many separate institutions rather than one building.", src: ["unesco_ua","list"] },
  /* 107 */ /* 104 */ { name: "Azizia Madrasa Library", location: "Bihar Sharif, India", year: 2023, cause: "war", lat: 25.18, lon: 85.52, perp: "Ram Navami rioters", desc: "The library contained around 4,500 works that were all lost when it was set on fire during Ram Navami riots in March 2023. Among the losses were rare Islamic manuscripts and texts accumulated over generations at this historic madrasa in Bihar.", src: ["bbc_bihar","aljaz_bihar","list"] },
  /* 108 */ /* 105 */ { name: "Diana Tamari Sabbagh Library", location: "Gaza City, Palestine", year: 2023, cause: "war", lat: 31.5, lon: 34.46, perp: "Israeli military airstrike", desc: "The Diana Tamari Sabbagh Library and the Rashad Shawa Cultural Center that housed it were destroyed by an airstrike in November 2023. The library held collections documenting Palestinian literary and cultural heritage. Its destruction was part of the broader devastation of Gaza's cultural infrastructure.", src: ["gaza_inv","lap_gaza","gaza_wiki"] },
  /* 109 */ /* 106 */ { name: "Edward Said Public Library", location: "Beit Lahia, Palestine", year: 2023, cause: "war", lat: 31.55, lon: 34.5, perp: "Israeli military", desc: "The Edward Said Public Library in Beit Lahia was destroyed during the Gaza war. Named after the Palestinian-American intellectual, the library held collections serving the local community and preserving Palestinian cultural memory accumulated over generations.", src: ["lap_gaza","gaza_wiki"] },
  /* 110 */ /* 107 */ { name: "Gaza Libraries Combined (2023-24)", location: "Gaza, Palestine", year: 2023, cause: "war", lat: 31.505, lon: 34.47, perp: "Israeli military", isNew: true, approx: true, desc: "Beyond the Diana Tamari Sabbagh Library and Edward Said Public Library, numerous smaller libraries, school collections, university archives, and community reading rooms across Gaza were destroyed during the 2023-2024 conflict. The collective destruction represents a systematic loss of Palestinian documentary heritage and the erasure of cultural memory spanning generations.", src: ["lap_gaza","gaza_wiki"] },
  /* 111 */ /* 108 */ { name: "Islamic University of Gaza Library", location: "Gaza City, Palestine", year: 2023, cause: "war", lat: 31.5, lon: 34.45, perp: "Israeli airstrikes", isNew: true, desc: "The largest academic library in Gaza, holding a reported 1.5 million volumes alongside academic journals, rare documents and historical manuscripts. The university and its library were destroyed during the bombardment that began in late 2023.", src: ["lap_gaza","gaza_wiki"] },
  /* 112 */ /* 109 */ { name: "Great Omari Mosque Library", location: "Gaza City, Palestine", year: 2023, cause: "war", lat: 31.504, lon: 34.464, perp: "Israeli airstrikes", isNew: true, rescued: true, desc: "Attached to Gaza's oldest mosque and among the most important libraries in Palestine. Its rare books had survived the Crusades and the First World War before being destroyed in an airstrike. Volunteers began sorting salvageable fragments inside the ruined library in February 2026.", src: ["lap_gaza","gaza_wiki"] },
  /* 113 */ /* 110 */ { name: "Central Archives of Gaza City", location: "Gaza City, Palestine", year: 2023, cause: "war", lat: 31.508, lon: 34.452, perp: "Israeli bombardment", isNew: true, desc: "Destroyed in December 2023 along with thousands of historically significant documents. The Ottoman-era records held there were entirely destroyed and none were recovered during later excavation, a complete erasure of several centuries of municipal and legal memory.", src: ["lap_gaza","gaza_wiki"] },
  /* 114 */ /* 111 */ { name: "Mohamed Omer Bashir Centre Library", location: "Omdurman, Sudan", year: 2023, cause: "war", lat: 15.64, lon: 32.48, perp: "Sudanese civil war combatants", isNew: true, desc: "The library of the Mohamed Omer Bashir Centre for Sudanese Studies at Omdurman Ahlia University was burned in May 2023. It held original documents on Sudanese political and cultural history. The centre's head believed it was targeted deliberately to harm the university.", src: ["sudan_wiki","list"] },
  /* 115 */ /* 112 */ { name: "Sudan National Records Office and Sudan Library", location: "Khartoum, Sudan", year: 2023, cause: "war", lat: 15.5, lon: 32.56, perp: "Rapid Support Forces / Sudanese Armed Forces", isNew: true, desc: "Sudan's National Archives and National Library both sustained heavy damage during the fighting for Khartoum. Members of the Sudanese Writers Union have argued that the wider destruction of the country's heritage was intended to erase its history.", src: ["sudan_wiki","list"] },
  /* 116 */ { name: "New College of Florida Gender and Diversity Studies Library", location: "Sarasota, Florida, USA", year: 2024, cause: "govt", lat: 27.38, lon: -82.56, perp: "New College administration under state-appointed trustees", isNew: true, desc: "In August 2024 the contents of the gender and diversity studies library were removed and thrown into a dump truck while students were away on break. Books on queer theory, history and Jewish studies were discarded. It is the most recent record here, and among the clearest modern examples of a collection destroyed not by war or accident but by administrative decision.", src: ["newcollege","list"] },
  /* 117 */ /* 113 */ { name: "EBAF Archives, Gaza", location: "Rimal, Gaza City, Palestine", year: 2025, cause: "war", lat: 31.52, lon: 34.44, perp: "Israeli airstrike", isNew: true, desc: "On 14 September 2025 an airstrike hit the building housing the archives of the Ecole biblique et archeologique francaise, destroying research materials gathered over decades of excavation across the region.", src: ["lap_gaza","gaza_wiki"] },
  /* 118 */ /* 114 */ { name: "Sudan University College of Forestry Library", location: "Khartoum, Sudan", year: 2026, cause: "war", lat: 15.55, lon: 32.53, perp: "Rapid Support Forces", isNew: true, desc: "In February 2026 Sudan University of Science and Technology officials reported that the College of Forestry library had been burned, along with musical instruments, used as fuel. The university reported 258 million dollars in total war losses.", src: ["sudan_wiki","list"] }
];

/* ---- derived values, computed once so no page hardcodes them ---- */

/* Counts per cause. The cards and filters read these, so a category
   can never display a number that disagrees with the data. */
(function () {
  Object.keys(CAUSES).forEach(function (k) { CAUSES[k].count = 0; });
  LIBRARIES.forEach(function (d) { if (CAUSES[d.cause]) CAUSES[d.cause].count++; });
})();

var LIB_TOTAL = LIBRARIES.length;

/* Records where people acted to save part of the collection — carried it
   out, hid it, smuggled it, or passed it hand to hand. Flagged by hand;
   the criterion is human action at risk, not a lucky sprinkler. */
var LIB_RESCUED = LIBRARIES.filter(function (d) { return d.rescued; }).length;

var LIB_YEARS = (function () {
  var ys = LIBRARIES.map(function (d) { return d.year; });
  return { min: Math.min.apply(null, ys), max: Math.max.apply(null, ys) };
})();

var LIB_SPAN = LIB_YEARS.max - LIB_YEARS.min;

/* Share that were deliberate acts rather than accidents. Note this
   counts the fire bucket as accidental, though it does contain arson. */
var DELIBERATE_PCT = Math.round(
  LIBRARIES.filter(function (d) { return d.cause !== 'fire'; }).length / LIB_TOTAL * 100
);

/* map.html and timeline.html read d.loc; index.html reads d.location.
   Alias rather than rewrite three codebases. */
LIBRARIES.forEach(function (d) { d.loc = d.location; });

/* Stable ids, assigned after sorting so they always match position. */
LIBRARIES.forEach(function (d, i) { d.id = i + 1; });

/* Region-wide records, by id, for the map's dashed rings. */
var APPROX = {};
LIBRARIES.forEach(function (d) { if (d.approx) APPROX[d.id] = 1; });

/* Formatting helper every page needs. */
function yearLabel(y) { return y < 0 ? Math.abs(y) + ' BC' : y + ' AD'; }
